config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :applications

    get 'applications/:application_id/devices' => 'devices#index', as: :application_devices

    get 'devices/:device_id' => 'devices#show', as: :device

    post 'devices/:device_id/get_info' => 'devices#get_info', as: :device_get_info

    post 'devices/:device_id/fetch_logs' => 'devices#fetch_logs', as: :device_fetch_logs

    get 'devices/:device_id/logs' => 'devices#logs', as: :device_logs

    get 'devices/:device_id/download/:file' => 'devices#download_log', as: :device_download_log

    post 'devices/:device_id/configure_logger' => 'devices#configure_logger', as: :device_configure_logger

    get 'devices/:device_id/status_stats' => 'devices#status_stats', as: :device_status_stats
  end
end

app/models/application.rb
class Application < ApplicationRecord
  enum app_type: [:android, :ios]

  class << self
    def create_application_id
      SecureRandom.uuid
    end
  end
end

app/controllers/admin/applications_controller.rb
class Admin::ApplicationsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    applications = Application.all

    @applications = applications
  end

  def new
    @application = Application.new
  end

  def create
    application = params[:application]
    application = Application.new({
      app_id: Application.create_application_id,
      name: application['name'],
      app_type: application['app_type'].to_i
    })
    application.save!

    redirect_to action: 'index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/applications_helper.rb
module Admin::ApplicationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/applications/index.html.erb
<div class="content-header">
  <h1>应用</h1>
  <div class="container-actions"><%= link_to '添加', new_admin_application_path %></div>
</div>

<div style="margin-top: 20px;">
  <table id="applications" class="table">
    <thead>
      <tr>
        <td class="col-application">应用</td>
        <td class="col-type">类型</td>
        <td class="col-date">创建时间</td>
      </tr>
    </thead>
    <tbody>

      <% if @applications.length > 0 %>
        <% for application in @applications %>
          <tr id="application-<%= application.id %>">
            <td class="col-application">
              <div class="row">
                <div class="col-sm-12">
                  <span class="col-name">名称：</span>
                  <span class="col-value"><%= application.name %></span>
                </div>
                <div class="col-sm-12">
                  <span class="col-name">编号：</span>
                  <span class="col-value"><%= application.app_id %></span>
                </div>                            
                <div class="col-sm-12 row-actions">
                  <%= link_to '查看', admin_application_devices_path(application.id) %>
                </div>
              </div>
            </td>
            <td class="col-type">
              <div class="row">
                <div class="col-sm-12">
                    <span class="col-value"><%= t(application.app_type) %></span>
                </div>
              </div>
            </td>
            <td class="col-date"><%= application.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          </tr>
        <% end %>
      <% else %>
        <tr><td colspan="3">当前没有应用</td></tr>
      <% end %>

    </tbody>
    <tfoot>
        <td class="col-application">应用</td>
        <td class="col-type">类型</td>
        <td class="col-date">创建时间</td>
    </tfoot>
  </table>
</div>

app/views/admin/applications/new.html.erb
<div class="content-header">
  <h1>添加应用</h1>
  <div class="container-actions"><%= link_to '取消', admin_applications_path %></div>
</div>

<div style="margin-top: 20px;">
  <%= form_for(@application, :url => admin_applications_path) do |f| %>
    <div class="form-group">
      <%= f.label :name, '名称' %>
      <div style="max-width: 300px;">
        <%= f.text_field :name, :autofocus => true, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :app_type, '类型' %>
      <div>
        <%= f.select :app_type, Application.app_types %>
      </div>
    </div>
    <%= f.submit '添加', :class => 'btn btn-primary' %>
  <% end %>
</div>