config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :applications

    get 'applications/:application_id/devices' => 'devices#index', as: :application_devices

    get 'devices/:device_id' => 'devices#show', as: :device

    post 'devices/:device_id/get_info' => 'devices#get_info', as: :device_get_info

    post 'devices/:device_id/fetch_logs' => 'devices#fetch_logs', as: :device_fetch_logs

    get 'devices/:device_id/logs' => 'devices#logs', as: :device_logs

    get 'devices/:device_id/download/:file' => 'devices#download_log', as: :device_download_log

    post 'devices/:device_id/configure_logger' => 'devices#configure_logger', as: :device_configure_logger

    get 'devices/:device_id/status_stats' => 'devices#status_stats', as: :device_status_stats
  end
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :application
end

app/controllers/admin/devices_controller.rb
MAX_COUNT_PER_PAGE = 15

class Admin::DevicesController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    logger.debug params

    if params[:page].nil?
      current_page = 1
    else
      current_page = params[:page].to_i
    end

    online = nil
    unless params[:online].nil?
      online = params[:online] != 'false'
    end

    where_conds = {}
    application_id = params[:application_id].to_i
    where_conds['application_id'] = application_id

    unless online.nil?
      where_conds['online'] = online
    end

    query = Device
    if where_conds.size != 0
      query = query.where(where_conds)
    end
    devices = query.offset((current_page - 1) * MAX_COUNT_PER_PAGE).limit(MAX_COUNT_PER_PAGE)

    devices_total_count = 0
    if where_conds.size != 0
      devices_total_count = Device.where(where_conds).count
    else
      devices_total_count = Device.count
    end

    @devices = devices
    @online = online

    @devices_total_count = devices_total_count

    @application = Application.find(application_id)

    page_num = @devices_total_count / MAX_COUNT_PER_PAGE
    page_num += 1 if @devices_total_count % MAX_COUNT_PER_PAGE

    page_start, page_end = pagination(page_num, current_page, 8)

    @page_start = page_start
    @page_end = page_end
    @page_num = page_num
    @current_page = current_page
  end

  def show
    # TODO eager load device's application
    device = Device.find(params[:device_id].to_i)

    logs = get_logs

    @device = device
    @application = device.application
    @logs = logs
  end

  def get_info
    # TODO check if online
    send_command(params[:device_id], type: 'get_device_info')

    render json: {
      status: 1
    }
  end

  def fetch_logs
    send_command(params[:device_id], type: 'fetch_device_logs')

    render json: {
      status: 1
    }
  end

  def download_log
    logs_dir = File.join(Rails.application.device_logs_dir, "#{params[:device_id]}")

    path = File.join(logs_dir, "#{params[:file]}.#{params[:format]}")
    send_file(path)
  end

  def configure_logger
    log_level = params[:log_level].to_i
    log_sent_freq = params[:log_sent_freq].to_i
    send_command(params[:device_id], type: 'configure_logger', content: { log_level: log_level, log_sent_freq: log_sent_freq})

    render json: {
      status: 1
    }
  end

  def logs
    logs = get_logs

    render json: {
      status: 1,
      content: {
        logs: logs
      }
    }
  end

  def status_stats
    # TODO eager load device's application
    device = Device.find(params[:device_id].to_i)

    @device = device
    @application = device.application
  end

  private
    def pagination(page_num, current_page, showed_num)
      page_start = 1

      half = showed_num / 2
      if current_page > half
        page_start = current_page - half + 1
      end

      page_end = page_start + showed_num - 1
      if page_end > page_num
        page_end = page_num
      end

      [page_start, page_end]
    end

    def send_command(device_id, command = {})
      ActionCable.server.broadcast("from_captain:devices:#{device_id}", command)
    end

    def get_logs
      logs_dir = File.join(Rails.application.device_logs_dir, "#{params[:device_id]}")
      files = []
      begin
        Dir.foreach(logs_dir) do |file|
          next if file == '.' or file == '..'
          files << file
        end
      rescue Exception => e
      end

      files = files.sort { |x, y| y <=> x }

      logs = []
      files.each do |file|
        filename = file
        file = File.join(logs_dir, file)
        size = File.size(file)
        if size < 1024
          size = "#{size} B"
        elsif size < 1024 * 1024
          size = "%0.1f KB" % [size / 1024.0]
        else
          size = "%0.1f MB" % [size / 1024.0 / 1024.0]
        end

        time_format = '%Y-%m-%d %H:%M:%S'
        mtime = File.mtime(file).strftime(time_format)
            
        log = {
          name: filename,
          size: size,
          mtime: mtime
        }
        logs << log
      end
      logs
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
end

app/helpers/admin/devices_helper.rb
module Admin::DevicesHelper
  def device_online(online)
    if online.nil?
      '状态未知'
    elsif online
      '在线'
    else
      '离线'
    end
  end

  def device_parse_info(info)
    begin
      JSON.parse(info)
    rescue Exception => e
      {}
    end
  end

  def device_network(network)
    unless network.nil?
      case network
      when 1
        "Wi-Fi"
      when 2
        "Mobile" 
      when 3
        "Wimax"
      when 4
        "Ethernet"
      when 5
        "Bluetooth"
      else
        "Unknown"
      end
    end
  end

  def device_battery_info(battery_info)
    battery_remaining = nil
    battery_consume_rate = nil
    battery_source = nil
    if !battery_info.nil? and !battery_info.empty?
      battery_info = JSON.parse(battery_info)
      battery_remaining = "#{battery_info['percent']}%"

      case battery_info['power_source_type']
      when 1
        battery_source = 'Not Charging' 
      when 2
        battery_source = 'AC'
      when 3
        battery_source = 'USB'
      when 4
        battery_source = 'Wireless'
      else
        battery_source = 'Unknown'
      end

      unless battery_info['amount_consumed'].nil?
        battery_consume_rate = "#{battery_info['amount_consumed']} / #{battery_info['duration']} min"
      end
    end

    if battery_remaining.nil?
      battery_remaining = 'Not Got'
    end

    if battery_source.nil?
      battery_source = 'Not Got'
    end

    if battery_consume_rate.nil?
      battery_consume_rate = 'Not Got'
    end

    "Remaining #{battery_remaining}, Power Source #{battery_source}, Consume Rate #{battery_consume_rate}"
  end

  def device_log_level(level)
    if level.nil?
      content_tag(:input, '', type: 'text', name: 'log_level', placeholder: 'Not Got yet')
    else
      content_tag(:input, '', type: 'text', name: 'log_level', value: level)
    end
  end

  def device_log_sent_freq(freq)
    if freq.nil?
      content_tag(:input, '', type: 'text', name: 'log_sent_freq', placeholder: 'Not Got yet')
    else
      content_tag(:input, '', type: 'text', name: 'log_sent_freq', value: freq)
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/admin/devices/index.html.erb
<h1>设备</h1>
<div style="margin-top: 20px;" class="breadcrumb">
  <%= link_to '应用', admin_applications_path, class: "breadcrumb-link" %>
  <span class="breadcrumb-separator">/</span>
  <%= link_to @application.name, '#', class: "breadcrumb-link" %>
</div>  
<div style="margin-top: 20px;">
  <div>
    <span id="applicationId" style="display:none;" data-application-id="<%= @application.id %>"></span>
    <select name="online">
      <option value="-1"<% if @online.nil? %> selected="selected"<% end %>>所有状态的设备</option>
      <option value="true"<% if @online %> selected="selected"<% end %>>在线的设备</option>
      <option value="false"<% if @online == false %> selected="selected"<% end %>>离线的设备</option>
    </select>
    <button class="btn btn-primary btn-filter-devices" style="margin-left: 10px;">筛选</button>
  </div>
  <div style="margin-top: 5px;">
  总共<span class="device-total-count"><%= @devices_total_count %></span>个设备
  </div>
</div>

<div style="margin-top: 20px;">
  <table id="devices" class="table">
    <thead>
      <tr>
        <td class="col-order">设备</td>
        <td class="col-date">最后更新时间</td>
      </tr>
    </thead>
    <tbody>

      <% if @devices.length > 0 %>
        <% for device in @devices %>
          <% device_info = device_parse_info(device.info) %>
          <tr id="device-<%= device.id %>">
            <td class="col-device">
              <div class="row">
                <div class="col-sm-6">
                  <span class="col-name">生产商: </span>
                  <span id="deviceManufacturer" class="col-value">
                    <%= device_info['manufacturer'] %>
                  </span> 
                </div>
                <div class="col-sm-6">
                  <span class="col-name">Username: <span>
                  <span id="deviceUsername" class="col-value">
                    <%= device.username %>
                  </span>
                </div>                
                <div class="col-sm-6">
                  <span class="col-name">OS: </span>
                  <span id="deviceOS" class="col-value">
                    <%= device_info['os'] %>
                  </span>
                </div>
                <div class="col-sm-6">
                  <span class="col-name">Locale: </span>
                  <span id="deviceLocale" class="col-value">
                    <%= device_info['locale'] %>
                  </span>
                </div>                   
                <div class="col-sm-6">
                  <span class="col-name">App Version: </span>
                  <span id="deviceAppVersion" class="col-value">
                    <%= device_info['app_version'] %>
                  </span> 
                </div>                
                <div class="col-sm-6">
                  <span class="col-name">编号：</span>
                  <span class="col-value"><%= device.id %></span>
                </div>            
                <div class="col-sm-6">
                  <span class="col-name">状态：</span>
                  <span class="col-value col-status"><%= device_online(device.online) %></span>
                </div>
                <div class="col-sm-12 row-actions">
                  <%= link_to '查看', admin_device_path(device.id) %>
                </div>
              </div>
            </td>
            <td class="col-date"><%= device.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
          </tr>
        <% end %>
      <% else %>
        <tr><td colspan="3">设备列表为空</td></tr>
      <% end %>

    </tbody>
    <tfoot>
        <td class="col-order">设备</td>
        <td class="col-date">最后更新时间</td>
    </tfoot>
  </table>
</div>

<div class="container-pagination text-center">
  <nav>
    <ul class="pagination">

      <% if @current_page == 1 %>
      <li class="disabled">
        <a href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <% else %>
      <li>
        <a data-page="<%= @current_page - 1 %>" href="#">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <% end %>

      <% for i in @page_start..@page_end %>
        <% if i == @current_page %>
        <li class="active"><a><%= i %></a></li>
        <% else %>
        <li><a data-page="<%= i %>" href="#"><%= i %></a></li>
        <% end %>
      <% end %>

      <% if @current_page == @page_num %>
      <li class="disabled">
        <a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <% else %>
      <li>
        <a data-page="<%= @current_page + 1 %>" href="#"><span aria-hidden="true">&raquo;</span></a>
      </li>
      <% end %>

    </ul>
  </nav>
</div>

app/views/admin/devices/show.html.erb
<h1>设备</h1>
<div style="margin-top: 20px;" class="breadcrumb">
  <%= link_to '应用', admin_applications_path, class: "breadcrumb-link" %>
  <span class="breadcrumb-separator">/</span>
  <%= link_to @application.name, admin_application_devices_path(@application.id), class: "breadcrumb-link" %>
  <span class="breadcrumb-separator">/</span>
  <%= link_to '设备', '#', class: "breadcrumb-link" %>  
</div> 

<% device_info = device_parse_info(@device.info) %>
<div id="devicePrimaryInfoContainer" class="panel panel-primary line-height-big" style="margin-top: 20px;">
  <span id="deviceId" style="display:none" data-device-id="<%= @device.id %>"></span>
  <div class="panel-heading">
    <h3 class="panel-title">Device Primary Info</h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
          <span>Username: </span>
          <span id="deviceUsername">
            <%= @device.username %>
          </span>
        </div>
        <div class="col-sm-3">
          <span>Status: </span>
          <span id="deviceOnlineStatus">
            <%= device_online(@device.online) %>
          </span>
          <%= link_to '状态统计', admin_device_status_stats_path(@device.id), class: 'btn btn-info' %>
        </div>
        <div class="col-sm-3">
          <span>Locale: </span>
          <span id="deviceLocale">
            <%= device_info['locale'] %>
          </span>
        </div>
        <div class="col-sm-3">
          <span>Timezone: </span>
          <span>To Be Implemented</span>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <span>Manufacturer: </span>
          <span id="deviceManufacturer">
            <%= device_info['manufacturer'] %>
          </span> 
        </div>
        <div class="col-sm-3">
          <span>OS: </span>
          <span id="deviceOS">
            <%= device_info['os'] %>
          </span>
        </div>      
        <div class="col-sm-3">
          <span>App Version: </span>
          <span id="deviceAppVersion">
            <%= device_info['app_version'] %>
          </span> 
        </div>
      </div>
    </div>
  </div>
</div>

<div id="deviceExtraInfoContainer" class="panel panel-primary line-height-big">
  <div class="panel-heading">
    <h3 class="panel-title">Device Extra Info</h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-4">
          <span>Network Environment: <span>
          <span id="deviceNetwork">
            <%= device_network(device_info['network_type']) %>
          </span>
        </div>
        <div class="col-sm-12">
          <span>Battery Info: <span>
          <span id="deviceBatteryInfo">
            <%= device_battery_info(device_info['battery_info']) %>
          </span>
        </div>
        <div class="col-sm-6">
          <span>Data Cost In Wi-Fi Mode: </span><span>Unknown</span>
        </div>
        <div class="col-sm-6">
          <span>Data Cost In Roaming Mode: </span><span>Unknown</span>
        </div>
        <div class="col-sm-6">
          <span>CPU Usage: </span><span>Unknown</span>
        </div>
        <div class="col-sm-6">
          <span>Memory Usage: </span><span>Unknown</span>
        </div>      
        <div class="col-sm-6">
          <span>Storage Usage: </span><span>Unknown</span>
        </div>
        <div class="col-sm-6">
          <span>Updated at: </span>
          <span id="deviceUpdatedTime">
            <%= @device.updated_at.strftime('%Y-%m-%d %H:%M:%S') %>
          </span>
        </div>
        <div class="col-sm-12">
          <hr />
        </div>
        <div class="col-sm-12">
          <button class="btn btn-primary btn-fetch-new-info"><span class="glyphicon glyphicon-refresh spin"></span><span class="normal-text">获取新的信息</span><span class="spin-text">获取中...</span></button>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="deviceConfigurationContainer" class="panel panel-primary line-height-big">
  <div class="panel-heading">
    <h3 class="panel-title">Device Configuration</h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-5">
          <span>Current Log Level: <span>
          <%= device_log_level(device_info['log_level']) %>
        </div>
        <div class="col-sm-5">
          <span>Log Sent Freq(in seconds): <span>
          <%= device_log_sent_freq(device_info['log_sent_freq']) %>
        </div>
        <div class="col-sm-2">
          <button class="btn btn-primary btn-configure-logger">
            <span class="glyphicon glyphicon-refresh spin"></span><span class="normal-text">修改日志设置</span><span class="spin-text">修改中...</span>
          </button>
        </div>
      </div>
    </div>
  </div>  
</div>

<div id="deviceLogContainer" class="panel panel-primary container-log">
  <div class="panel-heading">
    <h3 class="panel-title">Device Log</h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <button class="btn btn-primary btn-fetch-logs">
            <span class="glyphicon glyphicon-refresh spin"></span><span class="normal-text">获取日志</span><span class="spin-text">获取中...</span>
          </button>
        </div>
        <div class="col-sm-12">
          <hr />
        </div>
      </div>
    </div>
    <div id="deviceLogs" class="container-fluid">
      <% @logs.each do |log| %>
      <div class="row">
        <div class="col-sm-2">
          <%= log[:name] %>
        </div>
        <div class="col-sm-8">
          <span>modified at <%= log[:mtime] %></span>
          <span>, size <%= log[:size] %></span>
        </div>
        <div class="col-sm-2">
          <%= link_to 'Download', admin_device_download_log_path(:device_id => @device.id, :file => log[:name]) %>
        </div>            
      </div>
      <% end %>
    </div>
  </div>  
</div>

app/views/admin/devices/status_stats.erb
<h1>设备</h1>
<div style="margin-top: 20px;" class="breadcrumb">
  <%= link_to '应用', admin_applications_path, class: "breadcrumb-link" %>
  <span class="breadcrumb-separator">/</span>
  <%= link_to @application.name, admin_application_devices_path(@application.id), class: "breadcrumb-link" %>
  <span class="breadcrumb-separator">/</span>
  <% if @device.username.empty? %>
  <%= link_to "设备 \##{@device.id}", admin_device_path(@device.id), class: "breadcrumb-link" %>  
  <% else %>
  <%= link_to "设备 \##{@device.id} (#{@device.username})", admin_device_path(@device.id), class: "breadcrumb-link" %>
  <% end %>
  <span class="breadcrumb-separator">/</span>
  <%= link_to '状态统计', '', class: "breadcrumb-link" %>  
</div>
<div id="stats">
</div>
<div>
  <h3>A simple timeline</h3>
  <div id="timeline1"></div>
</div>
<script type="text/javascript">
  $(function() {
    var status_records_in_json = <%= raw(@device.status_records) %>;
    d3.select('#stats').append('svg').attr('width', '100%');

    var testData = [
      {times: [{"starting_time": 1355752800000, "ending_time": 1355759900000}, {"starting_time": 1355767900000, "ending_time": 1355774400000}]},
      {times: [{"starting_time": 1355759910000, "ending_time": 1355761900000}, ]},
      {times: [{"starting_time": 1355761910000, "ending_time": 1355763910000}]}
    ];
    var width = 500;
    function timelineRect() {
      var chart = d3.timeline();

      var svg = d3.select("#timeline1").append("svg").attr("width", width)
        .datum(testData).call(chart);
    }

    timelineRect();
  });
</script>