config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  get 'admin' => 'admin#index'
  namespace :admin do
    resources :applications

    get 'applications/:application_id/devices' => 'devices#index', as: :application_devices

    get 'devices/:device_id' => 'devices#show', as: :device

    post 'devices/:device_id/get_info' => 'devices#get_info', as: :device_get_info

    post 'devices/:device_id/fetch_logs' => 'devices#fetch_logs', as: :device_fetch_logs

    get 'devices/:device_id/logs' => 'devices#logs', as: :device_logs

    get 'devices/:device_id/download/:file' => 'devices#download_log', as: :device_download_log

    post 'devices/:device_id/configure_logger' => 'devices#configure_logger', as: :device_configure_logger

    get 'devices/:device_id/status_stats' => 'devices#status_stats', as: :device_status_stats
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to t('admin.navigation.home'), admin_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<% if admin_signed_in? %>
				<li><%= link_to t('admin.navigation.applications'), admin_applications_path %></li>
				<li><%= link_to t('admin.navigation.sign_out'), destroy_admin_session_path, :method=>'delete' %></li>
				<% else %>
				<li><%= link_to t('admin.navigation.sign_in'), new_admin_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>common-projects</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

	<header>
		<%= render 'layouts/navigation' %>
	</header>
	<main role="main">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</main>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sakura</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>